# filepath: /home/devsys/ball-catching-game/.github/workflows/python-app.yml
name: Python Application CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-tk libglib2.0-dev binutils

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Package application
      run: |
        pyinstaller --onefile app.py
        ls -l dist

    - name: Debug dist directory
      run: |
        ls -l dist

    - name: Upload artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: ball-catching-game
        path: dist/app
