# filepath: /home/devsys/ball-catching-game/.github/workflows/python-app.yml
name: Python Application CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-tk libglib2.0-dev binutils

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Package application
      run: |
        pyinstaller --onefile --clean --log-level=DEBUG app.py || true
        ls -l dist || true
        ls -l build || true
        cat app.spec || true

    - name: Debug working directory
      run: |
        ls -l
